### ISSUE TITLE
[DISCUSSION] Reach of the CoC

### ISSUE THREAD

**Issue by TheFrozenFire** [derickr/php-code-of-conduct#27]
> The CoC is only about interaction with the PHP community. Your private and public lives outside of the PHP community are your own. However, we reserve the right to take your public conduct into account when considering your project related conduct.

This should read:

> The CoC is only about interaction within the official PHP mailing list and other official project resources. Your private and public lives outside of the PHP project are your own. However, we reserve the right to take your public conduct into account when considering your project related conduct.

Because the remainder of the CoC specifically prohibits things that most people don't consider offensive, I don't think it's reasonable to have this code applicable outside of official project resources. For instance, if I want to make dick jokes on IRC, that's none of your business. If I want to troll someone on /r/PHP, that's none of your business, even though I do have the "PHP Docs" tag next to my username.

To be clear, I'm not objecting to prohibiting people from engaging in _serious misconduct_  in relation to the project when off of PHP project resources. Nor am I objecting to restricting content on PHP project resources (I don't think anyone needs to make dick jokes on php.internals). But I am objecting to this CoC's overlap of the two restrictions.

Either make it clear that this applies only to official resources, or eliminate prohibitions on language and behaviour that is not actual misconduct. You can't have it both ways.

**Comment by padraic** [comment]
The section can be clarified, but it also needs to account for the purpose of the COC in plain language. The mailing list is not a valid limiting scope since it raises the question of whether conduct within the project but beyond the mailing list can be reported. The "only about interaction within" appears to say otherwise.

> Either make it clear that this applies only to official resources, or eliminate prohibitions on language and behaviour that is not actual misconduct. You can't have it both ways.

You should also clarify what language or behaviour you see covered, but is not misconduct.

**Comment by derickr** [comment]
I am disagreeing with the fact that this should be limited to the PHP internals mailinglist only. It should very much spill into the PHP IRC channels and also apply to _contributors_ harassing others on /r/PHP and twitter.

**Comment by TheFrozenFire** [comment]
If the most contentious over-reaches of the CoC can't be discussed, you really shouldn't expect any cooperation. If this remains as-is, I'd be voting to reject the RFC outright, and I'd be encouraging everyone to do the same.

Please don't close issues just because you disagree with the question being asked.

**Comment by AdamKyle** [comment]
> I am disagreeing with the fact that this should be limited to the PHP internals mailinglist only. It should very much spill into the PHP IRC channels and also apply to contributors harassing others on /r/PHP and twitter.

I love this. you shut down a conversation because you clearly don't want to deal with the back lash of the community who, some of, are greatly opposed to this. Instead you have the SJW on one shoulder and the femanazi's on the other.

Objective view the situation? I think not. What I think is that you sir are childish and should face up to the criticism of the community who [are greatly opposed](https://www.reddit.com/r/PHP/comments/48b41j/an_object_lesson_in_conduct_enforcement/) to this utter bull shit.
